import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { Script } from 'node:vm';

// This deliberately supports only this project's local modules. Unexpected module
// syntax fails the build instead of silently producing a broken installed plugin.
export async function build() {
  const root = new URL('../plugin/', import.meta.url);
  const sources = [];
  for (const name of ['report.js', 'book.js', 'changes.js', 'text-display.js', 'book-reports.js', 'rpc.js', 'navigation.js', 'toc-tree.js', 'book-search.js', 'editor-window.js', 'library-order.js', 'draft-storage.js', 'source-guard.js', 'app.js']) {
    const source = (await readFile(new URL(name, root), 'utf8'))
      .replace(/\r\n/g, '\n')
      .replace(/^export (?=(?:async )?function\s|const\s)/gm, '')
      .replace(/^import \{[^\n]+\} from '\.\/(?:report|book|changes|text-display|book-reports|rpc|navigation|toc-tree|book-search|editor-window|library-order|draft-storage|source-guard)\.js';\r?\n/gm, '');
    if (/^\s*(?:import|export)\b/m.test(source) || /\bimport\s*\(/.test(source)) {
      throw new Error(`Unsupported module syntax in ${name}`);
    }
    sources.push(source);
  }
  const bundle = `// Generated by scripts/build.mjs; edit the source modules instead.\n(function () {\n'use strict';\n${sources.join('\n')}\n})();\n`;
  new Script(bundle, { filename: 'app.bundle.js' });
  await writeFile(new URL('app.bundle.js', root), bundle, 'utf8');
  return bundle;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await build();
